do $$
declare
  seed_user_id uuid;
  project_id uuid;
  project_index integer;
  slot_index integer;
  pcm_count integer;
  project_status text;
  project_progress integer;
  project_deadline date;
  v_agent_name text;
  v_project_name text;
  v_pcm_file_name text;
  v_pcm_storage_path text;
  agents text[] := array[
    'Wendy Wu',
    'Distant Journeys',
    'WOC',
    'Travel Studio',
    'Asia Desk',
    'Europe Team',
    'Group Operations',
    'Product Support',
    'Finance Desk',
    'Contracting Hub'
  ];
begin
  select id
  into seed_user_id
  from auth.users
  order by created_at nulls last, id
  limit 1;

  if seed_user_id is null then
    raise notice 'Skipping demo project seed because no auth.users row exists.';
    return;
  end if;

  for project_index in 1..100 loop
    v_project_name := format('Demo Workflow Project %s', lpad(project_index::text, 3, '0'));
    v_agent_name := agents[((project_index - 1) % array_length(agents, 1)) + 1];
    project_status := (array['Product', 'Finance', 'Contracting', 'Completed'])[((project_index - 1) % 4) + 1];
    project_progress := case project_status
      when 'Product' then 25
      when 'Finance' then 55
      when 'Contracting' then 75
      else 100
    end;
    project_deadline := current_date + ((project_index % 70) - 25);

    select projects.id
    into project_id
    from public.projects
    where projects.user_id = seed_user_id
      and projects.project_name = v_project_name
    limit 1;

    if project_id is null then
      insert into public.projects (
        project_name,
        agent,
        channel,
        deadline,
        status,
        description,
        progress,
        assigned_to,
        priority,
        finance_status,
        contracting_status,
        product_status,
        notes,
        user_id
      )
      values (
        v_project_name,
        v_agent_name,
        'Demo',
        project_deadline,
        project_status,
        format('Seeded demo workflow project %s for dashboard and task table testing.', project_index),
        project_progress,
        v_agent_name,
        (array['Low', 'Medium', 'High'])[((project_index - 1) % 3) + 1],
        case when project_status in ('Finance', 'Contracting', 'Completed') then 'In review' else 'Not started' end,
        case when project_status in ('Contracting', 'Completed') then 'In progress' else 'Waiting' end,
        case when project_status = 'Completed' then 'Approved' else 'Open' end,
        'Generated by demo seed migration.',
        seed_user_id
      )
      returning id into project_id;
    end if;

    pcm_count := 3 + (project_index % 3);

    for slot_index in 1..pcm_count loop
      v_pcm_file_name := format(
        'Demo Project %s - PCM %s.xlsx',
        lpad(project_index::text, 3, '0'),
        slot_index
      );
      v_pcm_storage_path := format(
        '%s/demo-seed/%s/pcm-row-%s-v1.xlsx',
        seed_user_id,
        project_id,
        slot_index
      );

      if not exists (
        select 1
        from public.project_files
        where storage_path = v_pcm_storage_path
      ) then
        insert into public.project_files (
          project_id,
          user_id,
          storage_bucket,
          storage_path,
          file_name,
          file_stage,
          workflow_slot,
          version_number,
          uploaded_by,
          uploaded_at,
          is_current_version,
          file_type,
          file_size
        )
        values (
          project_id,
          seed_user_id,
          'project-files',
          v_pcm_storage_path,
          v_pcm_file_name,
          'PCM',
          slot_index,
          1,
          'Demo seed',
          now() - ((project_index + slot_index) * interval '1 hour'),
          true,
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          4096 + (project_index * 100) + slot_index
        );
      end if;
    end loop;
  end loop;
end $$;

notify pgrst, 'reload schema';
